services:
  - type: web
    name: hcv
    env: php
    plan: free
    branch: main
    region: frankfurt
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:$PORT -t ."
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
